<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="3" skipped="0" tests="13" time="0.062" timestamp="2024-11-30T19:30:30.874341+00:00" hostname="tom"><testcase classname="converter_test" name="test_celsius_to_fahrenheit" time="0.000" /><testcase classname="converter_test" name="test_celsius_to_kelvin" time="0.000" /><testcase classname="converter_test" name="test_fahrenheit_to_celsius" time="0.000"><failure message="assert 37.77777777777778 == 17.78&#10; +  where 37.77777777777778 = &lt;function Converter.fahrenheit_to_celsius at 0x0000022BC1023740&gt;(100)&#10; +    where &lt;function Converter.fahrenheit_to_celsius at 0x0000022BC1023740&gt; = Converter.fahrenheit_to_celsius">@pytest.mark.fahrenheit_to_celsius
    def test_fahrenheit_to_celsius():
        assert Converter.fahrenheit_to_celsius(32) == 0  # Passes (32°F = 0°C)
&gt;       assert Converter.fahrenheit_to_celsius(100) == 17.78  # Fail
E       assert 37.77777777777778 == 17.78
E        +  where 37.77777777777778 = &lt;function Converter.fahrenheit_to_celsius at 0x0000022BC1023740&gt;(100)
E        +    where &lt;function Converter.fahrenheit_to_celsius at 0x0000022BC1023740&gt; = Converter.fahrenheit_to_celsius

converter_test.py:20: AssertionError</failure></testcase><testcase classname="converter_test" name="test_fahrenheit_to_kelvin" time="0.000"><failure message="assert 373.15 == 375.15&#10; +  where 373.15 = &lt;function Converter.fahrenheit_to_kelvin at 0x0000022BC10237E0&gt;(212)&#10; +    where &lt;function Converter.fahrenheit_to_kelvin at 0x0000022BC10237E0&gt; = Converter.fahrenheit_to_kelvin">@pytest.mark.fahrenheit_to_kelvin
    def test_fahrenheit_to_kelvin():
        assert Converter.fahrenheit_to_kelvin(32) == 273.15   # Passes (32°F = 273.15K)
&gt;       assert Converter.fahrenheit_to_kelvin(212) == 375.15  # Fail (Expected 373.15K)
E       assert 373.15 == 375.15
E        +  where 373.15 = &lt;function Converter.fahrenheit_to_kelvin at 0x0000022BC10237E0&gt;(212)
E        +    where &lt;function Converter.fahrenheit_to_kelvin at 0x0000022BC10237E0&gt; = Converter.fahrenheit_to_kelvin

converter_test.py:26: AssertionError</failure></testcase><testcase classname="converter_test" name="test_kelvin_to_celsius" time="0.000" /><testcase classname="converter_test" name="test_kelvin_to_fahrenheit" time="0.000" /><testcase classname="converter_test" name="test_eur_to_usd" time="0.000" /><testcase classname="converter_test" name="test_eur_to_gbp" time="0.000" /><testcase classname="converter_test" name="test_eur_to_jpy" time="0.000" /><testcase classname="converter_test" name="test_eur_to_aud" time="0.000" /><testcase classname="converter_test" name="test_eur_to_cad" time="0.000" /><testcase classname="converter_test" name="test_eur_to_inr" time="0.000" /><testcase classname="converter_test" name="test_validate_currency_input_valid" time="0.000"><failure message="assert 100 == -100&#10; +  where 100 = validate_currency_input(100)">@pytest.mark.currency_validation
    def test_validate_currency_input_valid():
&gt;       assert validate_currency_input(100) == -100  # unvalid negative amount
E       assert 100 == -100
E        +  where 100 = validate_currency_input(100)

converter_test.py:79: AssertionError</failure></testcase></testsuite></testsuites>